### ISSUE TITLE
Compiling rejson.so with make *** No rule to make target 'all'.  Stop.

### ISSUE THREAD

**Issue by ghothan** [RedisJSON/RedisJSON#174] opened 2020-04-29 19:31 UTC
Hello,

I am following the instructions for compiling the RedisJSON module via this site: https://oss.redislabs.com/redisjson/

When I run the make command I get the following output:

root@ip-10-53-10-58:/tmp/RedisJSON# make
make -C ./src all
make[1]: Entering directory '/tmp/RedisJSON/src'
make[1]: *** No rule to make target 'all'.  Stop.
make[1]: Leaving directory '/tmp/RedisJSON/src'
Makefile:2: recipe for target 'all' failed
make: *** [all] Error 2
root@ip-10-53-10-58:/tmp/RedisJSON#

Is there a different way to compile the module?  I've tried compiling via the cargo command as well but that seems to error out before finishing.  Thank you very much for your time and dedication to this project!

**Comment by gkorland** [comment] 2020-04-29 19:46
@Blastwaive sorry to confusion, we're working on fixing the documentation.
Notice, these build instruction are referring to the GA version [1.0.4](https://github.com/RedisJSON/RedisJSON/releases/tag/v1.0.4). 
You should checkout the 1.0 branch `git checkout 1.0` before calling `make`.
To build the master branch you need to call `cargo build --release`

Can you please add the error you got when calling `cargo build --release`?

**Comment by ghothan** [comment] 2020-04-29 20:54
No problem at all, Guy.  Attached is the out put I received after running `/RedisJSON cargo build --release` 

I did checkout the 1.0 branch and call `make`.  It appears to have compiled everything without issue.  However, when running `make test` I received the following at the end of the terminal output:

111 JSON files validated, 0 problems detected
make -C pytest
make[2]: Entering directory '/tmp/RedisJSON/test/pytest'
python -m unittest discover -v
make[2]: python: Command not found
Makefile:2: recipe for target 'test' failed
make[2]: *** [test] Error 127
make[2]: Leaving directory '/tmp/RedisJSON/test/pytest'
Makefile:72: recipe for target 'unittest' failed
make[1]: *** [unittest] Error 2
make[1]: Leaving directory '/tmp/RedisJSON/test'
Makefile:5: recipe for target 'test' failed
make: *** [test] Error 2 

[cargo build --release error.txt](https://github.com/RedisJSON/RedisJSON/files/4554551/cargo.build.--release.error.txt)

**Comment by gkorland** [comment] 2020-04-29 21:17
As for branch 1.0 it seems like you don't have python installed for the tests
```
 make[2]: python: Command not found
```

As for master it seems like you don't have clang installed. (you'll need python too for the tests)

```
--- stderr
thread 'main' panicked at 'Unable to find libclang: "couldn\'t find any valid shared libraries matching: [\'libclang.so\', \'libclang-*.so\', \'libclang.so.*\'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', src/libcore/result.rs:1188:5
```

**Comment by gkorland** [comment] 2020-04-30 20:35
@ghothan did you mange ? Can I close this issue?

**Comment by ghothan** [comment] 2020-04-30 20:38
@gkorland I did manage to get the rejson.so file to build; both with `make `and `cargo build --release`.  

Thank you very much for your help.  Have a great weekend!

**Comment by Blastwaive** [comment] 2020-05-02 12:19
Yes, the issue is now resolved.  

Thanks a bunch!

**Closed** 2020-05-06 06:54 UTC
Labels: help wanted
