### ISSUE TITLE
Unconventional JSON.GET behaviour when the path does not exist

### ISSUE THREAD

**Issue by axelpale** [RedisJSON/RedisJSON#74] opened 2018-06-27 17:10 UTC
**ReJSON version:** 1.0.2
**Redis version:** 4.0.10

The behavior of JSON.GET is inconsistent with JSON.MGET, built-in GET, and JavaScripts interpreters when an object key on the path does not exist. JSON.GET returns an error instead of `nil` which leads to the anti-pattern of using exceptions as a part of the control flow.

Consider the following example where the key `foo` does not exist and the key `bar` contains JSON `{"baz": {"biz": "qux"}}`. Let us try to access the missing key `foo` first:

    > GET foo
    (nil)
    > JSON.GET foo
    (nil)
    > JSON.MGET foo
    (empty list or set)
    > JSON.MGET foo .
    1) (nil)

Okay, mostly nils. Let us then access a missing object key within the existing key `bar`.

    > JSON.MGET bar foo
    1) (nil)
    > JSON.GET bar foo
    (error) ERR key 'foo' does not exist at level 0 in path
    > JSON.MGET bar baz.foo
    1) (nil)
    > JSON.GET bar baz.foo
    (error) ERR key 'foo' does not exist at level 1 in path

Spot the inconsistensies of JSON.GET? Finally, let us try how similar JavaScript object behave in Node.js interpreter:

    > foo
    ReferenceError: foo is not defined
    > foo.bar
    ReferenceError: foo is not defined
    > bar.foo
    undefined
    > bar.baz
    { biz: 'qux' }
    > bar.foo.biz
    TypeError: Cannot read property 'biz' of undefined

A nullish value `undefined` is returned when the last part of the path does not exist.

In addition, the behaviour of JSON.GET forces the programmer to use the error as a part of the program control flow. Using exceptions as part of the control flow is [a known anti-pattern](https://softwareengineering.stackexchange.com/q/189222/167174). For example, sometimes the server must return a default document if the path does not exist. Here the non-existent path is not necessarily a sign of an error, it is just a part of the state.

As a last note, one could erroneusly think that without an error it is hard to differentiate between a missing key and a null value. This is false because a missing key should return `(nil)` and an existing key with null JSON string returns a string `"null"`.

I would like to see `JSON.GET foo` to return `(nil)` that seems to be the convention and not an anti-pattern.

**Comment by itamarhaber** [comment] 2018-07-01 12:35
Hello @axelpale 

Thanks for the detailed issue report. I honestly remember making the decision to err on non-existant paths in JSON.GET, but I can't remember the reasoning :)

Your analysis and recommendation make sense to me. However, since this is a breaking change it should not be done without some consideration and possibly more feedback.

I suggest we keep this issue open for a while to give other users a chance to opine on it.

**Comment by axelpale** [comment] 2018-07-01 13:02
Hi, sounds good, thanks for the consideration.

Yes, it is a major change that would imply bump to v2.0.0 if we strictly follow [the semantic versioning](https://semver.org/). However the current **documentation does not specify** the behavior of JSON.GET when the path is missing. Therefore, in a way, both the error and `(nil)` fullfil the documented specification of v1. On the other hand, the test suite has [a case for the error behaviour](https://github.com/RedisLabsModules/rejson/blob/master/test/pytest/test.py#L181). If we deem the **test suite to be the true specification** then we need to bump to v2. Just thinking :)

**Comment by itamarhaber** [comment] 2018-07-01 13:13
Semantic versioning, imo, is taken too seriously and the implementation supersedes any documentation :)

Bumping the major version and correcting the tests (+ documenting) are indeed what's needed - thanks for your thoughts 👍

**Comment by glassfox** [comment] 2019-04-03 16:55
+1
The must have future.

**Comment by DmitrySergeyev** [comment] 2020-03-19 12:07
+1
Very unexpected behavior with throwing error for nonexistent keys.
This is still relevant in 2020, at least for me.

**Comment by axelpale** [comment] 2020-04-20 16:50
Great to hear this got solved!

**Comment by glassfox** [comment] 2020-09-10 05:07
Hi, trying to test the new behavior. Latest build still throw general error in case of part of the path not exist.

**Comment by Indexu** [comment] 2020-11-02 14:03
Using the latest Docker image and this problem is still an issue.
I'm assuming this got fixed, but then accidentally re-introduced.

Looking at the `jsonpath_lib` field in the `Cargo.toml` file, it seems like the fix was made in the `overflow-fix` branch in the repo https://github.com/gkorland/jsonpath
Without knowing any implementation specifics and purely going on timestamps, I'm guessing [this is the commit](https://github.com/gkorland/jsonpath/commit/9918581c16926b07c954163a3be74a991977047a) that fixed it.

However, since then the `jsonpath_lib` field has changed to the `public-parser` branch in the repo https://github.com/RedisJSON/jsonpath

It's possible that the currently used `jsonpath_lib` doesn't include this fix.

I'm also skeptical of the [test case](https://github.com/RedisJSON/RedisJSON/commit/dbdd4129d11584ce69df58e0e616c8f634ec5864) for this issue.
It seems to be adding to the root a key called `test` and the value as `{}` and then sets the key `$a` to `12` inside `test`, so the value for `test` will be `{"$a": 12}`.
Is the second `JSON.SET` supposed to be `JSON.GET`?
If so, that could explain how this went under the radar and got re-introduced.

Maybe @gkorland has more info?

**Comment by Kamil93** [comment] 2021-08-01 10:08
I can confirm bug still exists. When getting unexisted property of existed root, error is thrown instead of undefined (or nil in lua)

**Comment by casret** [comment] 2021-08-16 23:37
I too would like this behaviour.  Should we re-open this bug?

**Comment by emmanuelkeller** [comment] 2021-08-23 10:08
Thanks for your feedback. I confirm this inconsistency is going to be fixed in the up coming 2.0 release

**Comment by keywinf** [comment] 2022-02-02 22:01
Hi, 

Using the docker image redislabs/rejson:2.0.6 still throws this error for me. Any news on this?

**Comment by oshadmi** [comment] 2022-02-03 08:40
@keywinf 
Please try jsonpath beginning with `$`, e.g., 
```
127.0.0.1:6379> json.get bar $.baz.foo
"[]"
127.0.0.1:6379> json.get bar baz.foo $.baz
"{\"baz.foo\":[],\"$.baz\":[{\"biz\":\"qux\"}]}"
127.0.0.1:6379> json.get bar baz.foo $.bazzz
"{\"$.bazzz\":[],\"baz.foo\":[]}"
127.0.0.1:6379> json.mget bar baz $
1) "[{\"baz\":{\"biz\":\"qux\"}}]"
2) (nil)
127.0.0.1:6379> json.mget bar baz $.zz
1) "[]"
2) (nil)

```

Missing path, where allowed, defaults to the previous 1.x behavior with `.` and not `$`
See also [doc](https://oss.redis.com/redisjson/path/#redisjson-path)

**Comment by keywinf** [comment] 2022-02-03 09:03
I tried it before your comment, and it works pretty good. Thanks for confirmation and your quick reply!

**Closed** 2022-03-21 14:40 UTC
Labels: no-issue-activity

**Comment by gkorland** [comment] 2022-03-22 06:26
Please see @oshadmi last comment
