### ISSUE TITLE
[Bug]: The RDB file contains AUX module data I can't load: no matching module 'scdtype00'

### ISSUE THREAD

**Issue by CasaPas** [RedisJSON/RedisJSON#845] opened 2022-10-28 11:50 UTC
name: Bug Report
description: File a bug report
title: "[Bug]: The RDB file contains AUX module data I can't load: no matching module 'scdtype00'"
labels: [bug, triage]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

  - type: input
    id: operating_system
    attributes:
      label: OS
      description: UNRAID / Docker
      placeholder: linux

Following the last update (early morning) I get the following error from the docker log;

```
1:C 28 Oct 2022 12:45:04.938 # oO0OoO0OoO0Oo Redis is starting oO0OoO0OoO0Oo
1:C 28 Oct 2022 12:45:04.938 # Redis version=6.2.7, bits=64, commit=00000000, modified=0, pid=1, just started
1:C 28 Oct 2022 12:45:04.938 # Configuration loaded
1:M 28 Oct 2022 12:45:04.938 * monotonic clock: POSIX clock_gettime
1:M 28 Oct 2022 12:45:04.938 # A key '__redis__compare_helper' was added to Lua globals which is not on the globals allow list nor listed on the deny list.
1:M 28 Oct 2022 12:45:04.938 * Running mode=standalone, port=6379.
1:M 28 Oct 2022 12:45:04.939 # Server initialized
1:M 28 Oct 2022 12:45:04.939 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.
1:M 28 Oct 2022 12:45:04.939 * <ReJSON> version: 20400 git sha: e383c08 branch: HEAD
1:M 28 Oct 2022 12:45:04.939 * <ReJSON> Exported RedisJSON_V1 API
1:M 28 Oct 2022 12:45:04.939 * <ReJSON> Exported RedisJSON_V2 API
1:M 28 Oct 2022 12:45:04.939 * <ReJSON> Enabled diskless replication
1:M 28 Oct 2022 12:45:04.939 * <ReJSON> Created new data type 'ReJSON-RL'
1:M 28 Oct 2022 12:45:04.939 * Module 'ReJSON' loaded from /usr/lib/redis/modules/rejson.so
1:M 28 Oct 2022 12:45:04.939 * Loading RDB produced by version 6.2.7
1:M 28 Oct 2022 12:45:04.939 * RDB age 27879 seconds
1:M 28 Oct 2022 12:45:04.939 * RDB memory usage when created 1.09 Mb
1:M 28 Oct 2022 12:45:04.939 # The RDB file contains AUX module data I can't load: no matching module 'scdtype00'
```

And this is form the container log;

```
{"log":"1:M 28 Oct 2022 12:32:11.358 # WARNING overcommit_memory is set to 0! Background save may fail under low memory condition. To fix this issue add 'vm.overcommit_memory = 1' to /etc/sysctl.conf and then reboot or run the command 'sysctl vm.overcommit_memory=1' for this to take effect.\n","stream":"stdout","time":"2022-10-28T11:32:11.35845239Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * \u003cReJSON\u003e version: 20400 git sha: e383c08 branch: HEAD\n","stream":"stdout","time":"2022-10-28T11:32:11.358621205Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * \u003cReJSON\u003e Exported RedisJSON_V1 API\n","stream":"stdout","time":"2022-10-28T11:32:11.358624972Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * \u003cReJSON\u003e Exported RedisJSON_V2 API\n","stream":"stdout","time":"2022-10-28T11:32:11.358627276Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * \u003cReJSON\u003e Enabled diskless replication\n","stream":"stdout","time":"2022-10-28T11:32:11.35862937Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * \u003cReJSON\u003e Created new data type 'ReJSON-RL'\n","stream":"stdout","time":"2022-10-28T11:32:11.358631414Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * Module 'ReJSON' loaded from /usr/lib/redis/modules/rejson.so\n","stream":"stdout","time":"2022-10-28T11:32:11.358652243Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * Loading RDB produced by version 6.2.7\n","stream":"stdout","time":"2022-10-28T11:32:11.358981488Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * RDB age 27106 seconds\n","stream":"stdout","time":"2022-10-28T11:32:11.358986167Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 * RDB memory usage when created 1.09 Mb\n","stream":"stdout","time":"2022-10-28T11:32:11.358988291Z"}
{"log":"1:M 28 Oct 2022 12:32:11.358 # The RDB file contains AUX module data I can't load: no matching module 'scdtype00'\n","stream":"stdout","time":"2022-10-28T11:32:11.358990284Z"}
```

Any ideas?

**Comment by oshadmi** [comment] 2022-10-28 13:50
Related https://github.com/RediSearch/RediSearch/issues/3120

**Comment by CasaPas** [comment] 2022-10-28 18:32
So the solution to this error is  deleting the **dump.rdb** file.

I'm on UNRAID so the file is **user/appdata/TubeArchivist/redis/dump.rdb** and all is good (running :latest)

**Comment by rafie** [comment] 2022-12-12 09:37
Hello @CasaPas,
This happens because redisearch.so not being loaded into redis-server.
Not a bug, closing.

**Closed by rafie** 2022-12-12 09:37 UTC
