### ISSUE TITLE
Build Failed on Freebsd

### ISSUE THREAD

**Issue by fundon** [RedisJSON/RedisJSON#266] opened 2021-02-19 04:26 UTC
```
Running `/home/pili/.cargo/bin/sccache rustc --crate-name redis_module --edition=2018 /home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redis-module-0.11.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C embed-bitcode=no --cfg 'feature="default"' --cfg 'feature="experimental-api"' -C metadata=73dd5b62eca380f0 -C extra-filename=-73dd5b62eca380f0 --out-dir /usr/home/pili/libs/RedisJSON/target/release/deps -L dependency=/usr/home/pili/libs/RedisJSON/target/release/deps --extern bitflags=/usr/home/pili/libs/RedisJSON/target/release/deps/libbitflags-591696a7575fb36a.rmeta --extern enum_primitive_derive=/usr/home/pili/libs/RedisJSON/target/release/deps/libenum_primitive_derive-db7eb5d51710deec.so --extern libc=/usr/home/pili/libs/RedisJSON/target/release/deps/liblibc-2b3bdebbeffc79a7.rmeta --extern num_traits=/usr/home/pili/libs/RedisJSON/target/release/deps/libnum_traits-a4f92d27dea15b43.rmeta --extern strum_macros=/usr/home/pili/libs/RedisJSON/target/release/deps/libstrum_macros-7580dafec25f623d.so --cap-lints allow -L native=/usr/home/pili/libs/RedisJSON/target/release/build/redis-module-efeb12eba33fc2d9/out -l static=redismodule`
The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)

error: failed to run custom build command for `redisearch_api v0.5.0`

Caused by:
  process didn't exit successfully: `/usr/home/pili/libs/RedisJSON/target/release/build/redisearch_api-7501c95fe6e612b6/build-script-build` (exit code: 101)
  --- stdout
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
  running: "cmake" "/usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch" "-DRS_BUILD_STATIC=ON" "-DGIT_DESCRIBE_VERSION=0.0.0" "-DCMAKE_INSTALL_PREFIX=/usr/home/pili/libs/RedisJSON/target/release/build/redisearch_api-fc86437c03e76165/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_C_COMPILER=/usr/bin/cc" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_CXX_COMPILER=/usr/bin/c++" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC -m64" "-DCMAKE_ASM_COMPILER=/usr/bin/cc" "-DCMAKE_BUILD_TYPE=Release"
  -- The C compiler identification is Clang 11.0.1
  -- The CXX compiler identification is Clang 11.0.1
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /usr/bin/cc - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /usr/bin/c++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Performing Test HAVE_W_INCOMPATIBLE_POINTER_TYPES
  -- Performing Test HAVE_W_INCOMPATIBLE_POINTER_TYPES - Success
  -- Performing Test HAVE_W_DISCARDS_QUALIFIERS
  -- Performing Test HAVE_W_DISCARDS_QUALIFIERS - Success
  -- Configuring done
  -- Generating done
  -- Build files have been written to: /usr/home/pili/libs/RedisJSON/target/release/build/redisearch_api-fc86437c03e76165/out/build
  running: "cmake" "--build" "." "--target" "redisearchS" "--config" "Release" "--"
  Scanning dependencies of target metaphone
  Scanning dependencies of target rmutil
  [  1%] Building C object src/dep/phonetics/CMakeFiles/metaphone.dir/double_metaphone.c.o
  Scanning dependencies of target friso
  [  1%] Building C object src/rmutil/CMakeFiles/rmutil.dir/alloc.c.o
  [  1%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso.c.o
  [  2%] Building C object src/rmutil/CMakeFiles/rmutil.dir/args.c.o
  Scanning dependencies of target rscore
  [  2%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_exec.c.o
  [  2%] Building C object src/rmutil/CMakeFiles/rmutil.dir/heap.c.o
  [  3%] Building C object src/rmutil/CMakeFiles/rmutil.dir/periodic.c.o
  [  4%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_plan.c.o
  [  4%] Building C object src/rmutil/CMakeFiles/rmutil.dir/priority_queue.c.o
  [  5%] Building C object src/rmutil/CMakeFiles/rmutil.dir/sds.c.o
  [  6%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_array.c.o
  [  6%] Building C object CMakeFiles/rscore.dir/src/aggregate/aggregate_request.c.o
  [  6%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_hash.c.o
  [  7%] Building C object src/rmutil/CMakeFiles/rmutil.dir/strings.c.o
  [  8%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_lexicon.c.o
  [  8%] Building C object src/rmutil/CMakeFiles/rmutil.dir/util.c.o
  [  8%] Built target metaphone
  [  9%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/exprast.c.o
  [ 10%] Building C object src/rmutil/CMakeFiles/rmutil.dir/vector.c.o
  [ 10%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_link.c.o
  [ 11%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_string.c.o
  [ 11%] Built target rmutil
  [ 11%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/expression.c.o
  [ 11%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_ctype.c.o
  Scanning dependencies of target snowball
  [ 13%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/libstemmer/libstemmer.c.o
  [ 14%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_UTF8.c.o
  [ 14%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/runtime/api.c.o
  [ 15%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/lexer.c.o
  [ 16%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/runtime/utilities.c.o
  [ 16%] Building C object src/dep/friso/CMakeFiles/friso.dir/friso_GBK.c.o
  [ 17%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_danish.c.o
  [ 17%] Building C object CMakeFiles/rscore.dir/src/aggregate/expr/parser.c.o
  [ 18%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/date.c.o
  [ 18%] Built target friso
  [ 18%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_dutch.c.o
  [ 18%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/function.c.o
  [ 19%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_english.c.o
  [ 19%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_finnish.c.o
  [ 20%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_french.c.o
  [ 21%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/math.c.o
  [ 21%] Building C object CMakeFiles/rscore.dir/src/aggregate/functions/string.c.o
  [ 21%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_german.c.o
  [ 22%] Building C object CMakeFiles/rscore.dir/src/aggregate/group_by.c.o
  [ 22%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducer.c.o
  [ 23%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_italian.c.o
  [ 23%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_norwegian.c.o
  [ 25%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_porter.c.o
  [ 26%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/count.c.o
  [ 26%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/count_distinct.c.o
  [ 26%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_portuguese.c.o
  [ 27%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_spanish.c.o
  [ 28%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/deviation.c.o
  [ 28%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/first_value.c.o
  [ 28%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_1_swedish.c.o
  [ 29%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_2_hungarian.c.o
  [ 30%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/minmax.c.o
  [ 31%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/quantile.c.o
  [ 31%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_ISO_8859_2_romanian.c.o
  [ 32%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_KOI8_R_russian.c.o
  [ 32%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/random_sample.c.o
  [ 32%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_arabic.c.o
  [ 33%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/sum.c.o
  [ 33%] Building C object CMakeFiles/rscore.dir/src/aggregate/reducers/to_list.c.o
  [ 34%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_danish.c.o
  [ 34%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_dutch.c.o
  [ 35%] Building C object CMakeFiles/rscore.dir/src/alias.c.o
  [ 36%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_english.c.o
  [ 36%] Building C object CMakeFiles/rscore.dir/src/buffer.c.o
  [ 38%] Building C object CMakeFiles/rscore.dir/src/byte_offsets.c.o
  [ 38%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_finnish.c.o
  [ 39%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_french.c.o
  [ 39%] Building C object CMakeFiles/rscore.dir/src/cndict_loader.c.o
  [ 40%] Building C object CMakeFiles/rscore.dir/src/concurrent_ctx.c.o
  [ 40%] Building C object CMakeFiles/rscore.dir/src/config.c.o
  [ 41%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_german.c.o
  [ 41%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_hungarian.c.o
  [ 42%] Building C object CMakeFiles/rscore.dir/src/cursor.c.o
  [ 42%] Building C object CMakeFiles/rscore.dir/src/debug_commads.c.o
  [ 43%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_italian.c.o
  [ 44%] Building C object CMakeFiles/rscore.dir/src/dep/cndict/cndict_data.c.o
  [ 44%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_norwegian.c.o
  [ 44%] Building C object CMakeFiles/rscore.dir/src/dep/hll/hll.c.o
  [ 45%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_porter.c.o
  [ 46%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/cesu8.c.o
  [ 46%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_portuguese.c.o
  [ 47%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_romanian.c.o
  [ 47%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/ducet.c.o
  [ 48%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/extra.c.o
  [ 48%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/strcoll.c.o
  [ 48%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_russian.c.o
  [ 50%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_spanish.c.o
  [ 51%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/strings.c.o
  [ 51%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_swedish.c.o
  [ 51%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/tofold.c.o
  [ 52%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_tamil.c.o
  [ 53%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/tolower.c.o
  [ 53%] Building C object src/dep/snowball/CMakeFiles/snowball.dir/src_c/stem_UTF_8_turkish.c.o
  [ 54%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/toupper.c.o
  [ 54%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf16.c.o
  [ 55%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf16be.c.o
  [ 55%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf16he.c.o
  [ 56%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf16le.c.o
  [ 56%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf32.c.o
  [ 57%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf32be.c.o
  [ 57%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf32he.c.o
  [ 58%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf32le.c.o
  [ 58%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/utf8.c.o
  [ 59%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/validate.c.o
  [ 59%] Building C object CMakeFiles/rscore.dir/src/dep/libnu/version.c.o
  [ 60%] Building C object CMakeFiles/rscore.dir/src/dep/miniz/miniz.c.o
  [ 60%] Building C object CMakeFiles/rscore.dir/src/dep/thpool/thpool.c.o
  [ 61%] Building C object CMakeFiles/rscore.dir/src/dep/triemap/triemap.c.o
  [ 61%] Building C object CMakeFiles/rscore.dir/src/dictionary.c.o
  [ 61%] Built target snowball
  [ 63%] Building C object CMakeFiles/rscore.dir/src/doc_table.c.o
  [ 63%] Building C object CMakeFiles/rscore.dir/src/document.c.o
  [ 64%] Building C object CMakeFiles/rscore.dir/src/document_add.c.o
  [ 64%] Building C object CMakeFiles/rscore.dir/src/document_basic.c.o
  [ 65%] Building C object CMakeFiles/rscore.dir/src/ext/default.c.o
  [ 66%] Building C object CMakeFiles/rscore.dir/src/extension.c.o
  [ 66%] Building C object CMakeFiles/rscore.dir/src/field_spec.c.o
  [ 67%] Building C object CMakeFiles/rscore.dir/src/fork_gc.c.o
  [ 67%] Building C object CMakeFiles/rscore.dir/src/forward_index.c.o
  [ 68%] Building C object CMakeFiles/rscore.dir/src/fragmenter.c.o

  --- stderr
  CMake Deprecation Warning at CMakeLists.txt:1 (CMAKE_MINIMUM_REQUIRED):
    Compatibility with CMake < 2.8.12 will be removed from a future version of
    CMake.

    Update the VERSION argument <min> value or use a ...<max> suffix to tell
    CMake that the project does not need compatibility with older versions.


  CMake Deprecation Warning at CMakeLists.txt:6 (CMAKE_POLICY):
    The OLD behavior for policy CMP0026 will be removed from a future version
    of CMake.

    The cmake-policies(7) manual explains that the OLD behaviors of all
    policies are deprecated and that a policy should be set to OLD only under
    specific short-term circumstances.  Projects should be ported to the NEW
    behavior and not rely on setting a policy to OLD.


  fatal: not a git repository (or any parent up to mount point /usr)
  Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
  0.0.0

  CMake Warning (dev) at CMakeLists.txt:165 (GET_TARGET_PROPERTY):
    Policy CMP0045 is not set: Error on non-existent target in
    get_target_property.  Run "cmake --help-policy CMP0045" for policy details.
    Use the cmake_policy command to set the policy and suppress this warning.

    get_target_property() called with non-existent target "example_extension".
  This warning is for project developers.  Use -Wno-dev to suppress it.

  CMake Warning:
    Manually-specified variables were not used by the project:

      CMAKE_ASM_COMPILER
      CMAKE_ASM_FLAGS


  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/dep/miniz/miniz.c:3030:9: warning: Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files. [-W#pragma-messages]
  #pragma message("Using fopen, ftello, fseeko, stat() etc. path for file I/O - this path may not support large files.")
          ^
  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/fork_gc.c:287:25: error: incomplete definition of type 'struct iovec'
    FGC_sendBuffer(gc, iov->iov_base, iov->iov_len);
                       ~~~^
  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/fork_gc.c:286:10: note: forward declaration of 'struct iovec'
    struct iovec *iov = arg;
           ^
  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/fork_gc.c:287:40: error: incomplete definition of type 'struct iovec'
    FGC_sendBuffer(gc, iov->iov_base, iov->iov_len);
                                      ~~~^
  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/fork_gc.c:286:10: note: forward declaration of 'struct iovec'
    struct iovec *iov = arg;
           ^
  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/fork_gc.c:302:20: error: variable has incomplete type 'struct iovec'
        struct iovec iov = {.iov_base = (void *)term, termLen};
                     ^
  /usr/home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/redisearch_api-0.5.0/RediSearch/src/fork_gc.c:302:14: note: forward declaration of 'struct iovec'
        struct iovec iov = {.iov_base = (void *)term, termLen};
               ^
  3 errors generated.
  gmake[3]: *** [CMakeFiles/rscore.dir/build.make:888: CMakeFiles/rscore.dir/src/fork_gc.c.o] Error 1
  gmake[3]: *** Waiting for unfinished jobs....
  1 warning generated.
  gmake[2]: *** [CMakeFiles/Makefile2:275: CMakeFiles/rscore.dir/all] Error 2
  gmake[1]: *** [CMakeFiles/Makefile2:224: CMakeFiles/redisearchS.dir/rule] Error 2
  gmake: *** [Makefile:137: redisearchS] Error 2
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 2

  build script failed, must exit now', /home/pili/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-7a04d2510079875b/cmake-0.1.45/src/lib.rs:894:5
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by fundon** [comment] 2021-02-19 04:49
Then I custom it.

```
.
├── redisearch-api-rs
├── RedisJSON

cd redisearch-api-rs
cd RediSearch
git pull origin 1.8
git cherry-pick -p 2ab5332e341b6c1c4c805f2f3e9522ad7deaf824

cd ../../RedisJSON/
#redisearch_api = "0.5"
redisearch_api = { path = "../redisearch-api-rs" }

cargo build --release -v
```

Build success!

But redis-server(6.0.10) crashed.

```
redis-cli
127.0.0.1:6379> json.set user1 $ '{"last":"Joe", "first":"Mc"}' INDEX person
OK
127.0.0.1:6379> json.set user2 $ '{"last":"Joan", "first":"Mc"}' INDEX person
OK
127.0.0.1:6379> json.index add person last $.last
OK
127.0.0.1:6379> JSON.QGET person Jo*
Could not connect to Redis at 127.0.0.1:6379: Connection refused
not connected>

```

**Comment by gkorland** [comment] 2021-02-19 21:40
Can you please add the server error?

**Comment by fundon** [comment] 2021-02-20 02:40
redis.log
```

# Modules
module:name=ReJSON,ver=999999,api=1,filters=0,usedby=[],using=[],options=[]

# Commandstats
cmdstat_json.index:calls=1,usec=80,usec_per_call=80.00
cmdstat_scan:calls=1,usec=7,usec_per_call=7.00
cmdstat_command:calls=1,usec=336,usec_per_call=336.00
cmdstat_json.set:calls=2,usec=34,usec_per_call=17.00

# Cluster
cluster_enabled:0

# Keyspace
db0:keys=2,expires=0,avg_ttl=0

------ CLIENT LIST OUTPUT ------
id=5 addr=127.0.0.1:22663 fd=8 name= age=33 idle=0 flags=N db=0 sub=0 psub=0 multi=-1 qbuf=0 qbuf-free=32768 argv-mem=0 obl=0 oll=0 omem=0 tot-mem=49830 events=r cmd=json.index user=default

------ REGISTERS ------
26135:M 20 Feb 2021 02:37:10.279 #
RAX:000000080261a0a8 RBX:0000000000000002
RCX:0000000000000003 RDX:0000000800da3880
RDI:0000000802609020 RSI:000000080084e090
RBP:00007fffdf1f9c80 RSP:00007fffdf1f9b40
R8 :ffffffffffffdf70 R9 :0000000800850120
R10:0000000000000061 R11:0000000000000002
R12:ffffffffffffff30 R13:0000000800ce02cc
R14:0000000800ce02c8 R15:0000000800ce11a8
RIP:00000008015f71f6 EFL:0000000000010206
CSGSFS:0000000000000043
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b4f) -> 0000000000000002
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b4e) -> 0000000000000010
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b4d) -> 0000000000000003
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b4c) -> 0000000800c3d3c8
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b4b) -> 000000000025a276
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b4a) -> 00007fffdf1f9bc0
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b49) -> 000000000025bca3
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b48) -> 0000000000000000
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b47) -> 0000000000000005
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b46) -> 0000000000000005
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b45) -> ffffffffffffffff
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b44) -> ffffffffffffff1a
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b43) -> 1a1a1a1a1a1a1a1a
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b42) -> 1a1a1a1a1a1a1a1a
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b41) -> 00000000002679c9
26135:M 20 Feb 2021 02:37:10.279 # (00007fffdf1f9b40) -> 00007fffdf1f9b70

------ MODULES INFO OUTPUT ------

------ DUMPING CODE AROUND EIP ------
Symbol: RedisModule_OnUnload (base: 0x8015e4770)
Module: /usr/local/etc/redis_modules.d/librejson.so (base 0x801480000)
$ xxd -r -p /tmp/dump.hex /tmp/dump.bin
$ objdump --adjust-vma=0x8015e4770 -D -b binary -m i386:x86-64 /tmp/dump.bin
------

=== REDIS BUG REPORT END. Make sure to include from START to END. ===

       Please report the crash by opening an issue on github:

           http://github.com/redis/redis/issues

  Suspect RAM error? Use redis-server --test-memory to verify it.
```



[redis-server.core.zip](https://github.com/RedisJSON/RedisJSON/files/6013993/redis-server.core.zip)

**Comment by chayim** [comment] 2021-03-03 07:34
@fundon What version of FreeBSD are you on?

**Comment by fundon** [comment] 2021-03-03 08:16
@chayim 

```
FreeBSD 13.0-BETA4
Redis server v=6.0.11 sha=00000000:0 malloc=libc bits=64 build=1fb25447e77c8911
```

Both v6.0.10 and v6.0.11 all crashed.

**Comment by alpintrekker** [comment] 2021-03-25 15:23
Hi @fundon, 

I have a very similar root cause to what you had in your original post:

`fatal: not a git repository `

However, I can't repeat your "custom it" procedure:
```
├── redisearch-api-rs
├── RedisJSON

cd redisearch-api-rs
cd RediSearch
git pull origin 1.8
git cherry-pick -p 2ab5332e341b6c1c4c805f2f3e9522ad7deaf824
```

In which directory did you do that?

**Comment by osokin** [comment] 2021-08-10 23:06
Hi there,

I've just committed databases/redisjson port into FreeBSD ports tree, https://cgit.FreeBSD.org/ports/commit/?id=e66f56f4af6a96b837853217f0d66b6f01e06381.

I believe this issue can be closed.

Thank you.

**Closed** 2021-12-19 20:16 UTC
